### ISSUE TITLE
Error with Ubuntu

### ISSUE THREAD

**Issue by Quinchu** [takeiteasy/xget#4]
xget.rb:358:in `expand_path': no implicit conversion of nil into String (TypeError)
	from xget.rb:358:in `<main>'

Getting this error with the newest update.

**Comment by takeiteasy** [comment]
It wasn't a problem with Ubuntu, rather a problem with my testing. Fixed it with another quick update -> 18da9851fe6403b12dfd10e6edd78ccab7312ce3
