### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by marioandluigi878** [takeiteasy/xget#7]
I know the script is quite old but this is the only one that works well for me
It works alright on linux but it dosen't seem to like windows maybe I'm doing something wrong?

PS C:\Users\Rainee> xget '#nibl@irc.rizon.net/ARUTHA-BATCH"|"1080p/1465..1490' --nick Rainee4
irc.rizon.net ->
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1465, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1466, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1467, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1468, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1469, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1470, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1471, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1472, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1473, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1474, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1475, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1476, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1477, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1478, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1479, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1480, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1481, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1482, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1483, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1484, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1485, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1486, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1487, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1488, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1489, * ]
  [ irc.rizon.net, #nibl, ARUTHA-BATCH|1080p, 1490, * ]

Preparing to download: [HorribleSubs] Fate Stay Night - Unlimited Blade Works - 00 [1080p].mkv
#<Thread:0x0000000005742ea8@C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/xget-2.1.4/bin/xget:607 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/xget-2.1.4/bin/xget:608:in `block (3 levels) in <top (required)>'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/xget-2.1.4/bin/xget:608:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
Traceback (most recent call last):
        1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/xget-2.1.4/bin/xget:608:in `block (3 levels) in <top (required)>'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/xget-2.1.4/bin/xget:608:in `fork': fork() function is unimplemented on this machine (NotImplementedError)

**Comment by takeiteasy** [comment]
Problem is that the program uses ```fork``` (on line 608) when starting the download. This doesn't work on Windows apparently. It'll work under Cygwin though, or using the Windows subsystem for Linux. There is also the option for editing the script to use ```Process.spawn``` and ```Process.wait``` instead of the ```fork``` and ```pid.wait``` but I haven't tried it since I don't use Windows for developing much though, so it'll be a while before I edit this myself. Feel free to submit a pull request if you want.

**Comment by marioandluigi878** [comment]
Just thought i add this in here as well loaded up a linux vm (mainly cause im too lazy to switch to my linux drive) 
rainee@RaineeVB ~ $ xget '#ZOMBIE-WAREZ@irc.abandoned-irc.net/Zombie-Butcher/141'
! ERROR: #ZOMBIE-WAREZ@irc.abandoned-irc.net/Zombie-Butcher/141 is not a valid XDCC address
 XDCC Address format: #chan@irc.serv.com/bot/pack(s) or ^/msg irc.serv.com bot xdcc send #id$

**Comment by takeiteasy** [comment]
I fixed your second problem, update and try it again, should work.
